tunnel: voidsky
credentials-file: C:\Users\kuhna\.cloudflared\a95556af-17a4-45b4-8e9d-bce672ea2ebe.json

ingress:
  - hostname: game.voidboxllc.com
    service: http://localhost:3000
  - service: http_status:404